# Generated by Django 3.2.15 on 2022-08-22 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0003_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
