# Generated by Django 3.2.15 on 2022-08-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0005_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='articleApp.Tag'),
        ),
    ]
