# Generated by Django 3.2.15 on 2022-08-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0006_auto_20220822_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(related_name='tag', to='articleApp.Tag'),
        ),
    ]
