# Generated by Django 3.2.15 on 2022-08-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0007_alter_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
