# Generated by Django 3.2.15 on 2022-08-22 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0008_article_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
