# Generated by Django 3.2.15 on 2022-08-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0012_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static'),
        ),
    ]
