# Generated by Django 3.2.15 on 2022-08-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0013_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_image'),
        ),
    ]
