# Generated by Django 3.2.15 on 2022-08-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0014_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='draft',
            field=models.BooleanField(null=True),
        ),
    ]
