# Generated by Django 3.2.15 on 2022-08-23 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0016_article_articaltags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='articaltags',
        ),
    ]
