# Generated by Django 3.2.15 on 2022-08-24 05:05

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0017_remove_article_articaltags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='choices_field',
            field=models.CharField(blank=True, default='', max_length=200, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
