# Generated by Django 3.2.15 on 2022-08-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articleApp', '0018_article_choices_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='choices_field',
        ),
    ]
